apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  # Add fields here
  webhook:
    operations: 
      - CREATE
      - UPDATE
      - DELETE
      - CONNECT
