name: Fast forward latest release

on:
  push:
    branches:
    - main
    paths:
    - VERSION

jobs:
  ff:
    name: Fast forward from main to latest release branch
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Set Up Environment Variables
      run: |
        RELEASE_BRANCH="release-$(cut -d '.' -f 1,2 VERSION)"
        echo "RELEASE_BRANCH=${RELEASE_BRANCH}" >> ${GITHUB_ENV}

    - name: Fast-forward main to latest release
      run: |
        git checkout ${RELEASE_BRANCH} || git checkout -b ${RELEASE_BRANCH}
        git merge --ff-only origin/main
        git push origin ${RELEASE_BRANCH}

    - name: Slack failure report
      uses: slackapi/slack-github-action@v1.26.0
      if: ${{ failure() }}
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ secrets.CODE_HEALTH_SLACK_WEBHOOK }}
      with:
        payload: |
          {"blocks": [{
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": ":failed: Gatekeeper Operator fast-forwarding failed: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow run>"
            }
          }]}
